fix(windows): fix appcrash on windows where darkmode is not supported
tauri-apps/tao pull request #1022
Opened 2024-11-27 15:15 UTC by Jnschrber

The changes resolve this bug: https://github.com/tauri-apps/tauri/issues/11674 where Tauri2 crashes immediately on Windows 10 LTSC 2016

2024-11-28 03:02 UTC, amrbashir requested changes
Thank you, could you also add a change file in `.changes` directory?

2024-11-28 03:02 UTC, amrbashir commented on src/platform_impl/windows/dark_mode.rs
> +        if *DARK_MODE_SUPPORTED {
we could wrap the whole function in `if *DARK_MODE_SUPPORTED` similar to how it is done in `try_window_theme` function

2024-11-28 07:35 UTC, Jnschrber commented on src/platform_impl/windows/dark_mode.rs
> +        if *DARK_MODE_SUPPORTED {
Hi,
please see my latest commit (https://github.com/tauri-apps/tao/pull/1022/commits/1f623298db2f59efcec3ee070b2a1c9dafe8e2ca), in which I have implemented your requested change.

2024-12-02 10:51 UTC, amrbashir approved these changes

2024-12-08 22:59 UTC, amrbashir commented on .changes/dark-mode.md
> +Windows: Executing the function allow_dark_mode_for_app only if darkmode is supported.
```suggestion
On Windows, fix crash on older windows versions that doesn't support dark mode.
```

2024-12-08 22:59 UTC, amrbashir approved these changes

2024-12-08 23:00 UTC, merged