feat: Allow more strings to parse to keycode
tauri-apps/tao pull request #229
Opened 2021-10-27 16:17 UTC by probablykasper

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Allow more strings to parse to keycode, for example allows `CmdOrCtrl+,` as an alternative to `CmdOrCtrl+Comma`

2021-10-27 16:53 UTC, amrbashir requested changes
<s>Thanks but I don't think I like there is two possible values for keys in `from_str`, it breaks consistency with `to_str`.ex:
```rs
let key = KeyCode::from_str("`"); //parsed as KeyCode::Backquote which is correct
key.to_str(); // will return "BACKQUOTE` instead of what you originally entered which is " `"
```
</s>

Apologies, disregard that, we don't have `KeyCode::to_str()` lol.

I guess there is only the comment I left and we can merge this.

2021-10-27 16:53 UTC, amrbashir commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
does these even exist ? I can't find `Enter` in the numbers row for example.

2021-10-27 17:55 UTC, kasper9n commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
It should at least be possible for them to exist on keyboards. There are a lot of weird key codes

2021-10-27 18:52 UTC, amrbashir commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
The meaning of the "NUM" prefix is that these keys exist in the numbers row which some of them don't and even if they do exist, they should have a different corresponding KeyCode. I don't see any benefits from adding this, so it is probably better to remove it.

2021-10-27 18:58 UTC, amrbashir requested changes

2021-10-27 18:58 UTC, amrbashir commented on src/keyboard.rs
> +      "NUM9" | "NUMPAD9" => KeyCode::Numpad9,
~~The `NUM0-9` should correspond to `KeyCode::Digit0-9` not `KeyCode::Numpad0-9`~~

2021-10-27 20:36 UTC, kasper9n commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
Ah, thought you were asking if `NumpadEnter` exists in the numpad, my bad.

In Electron the `num` prefix is for the numpad, so that's why I added it like this. Would be confusing if `num0` means `numpad0` in Electron and `0` in tao/tauri. If it's too ambiguous, I'll just remove the `NUM` prefix.

2021-10-27 22:25 UTC, amrbashir commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
We are not trying to follow electron blindly so there will be differences.

2021-10-27 22:57 UTC, kasper9n commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
Not suggesting that, just would never expect `num0` to not be the `numpad0` key (which is why I misunderstood you earlier). Wikipedia's numpad page even states that `Num 0` can be used for `numpad0` to remove ambiguity, so I think it would be a poor decision to parse `num0` as `0`. Will go and remove the `NUM` prefixes if you prefer.

2021-10-28 06:21 UTC, amrbashir commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
You do raise a valid concern though. lets wait on this PR a bit, I will properly review it again when I am back (2-3 days). I need to check our code base and other stuff that I can't do on my phone right now.

2021-11-01 08:46 UTC, amrbashir commented on src/keyboard.rs
> +      "NUMENTER" | "NUMPADENTER" => KeyCode::NumpadEnter,
Now that I got time to look at this, I think this PR is fine as is, thanks.

2021-11-01 08:46 UTC, amrbashir approved these changes

2021-11-03 20:18 UTC, merged