Fix: #239 Update webview2-com and windows crates
tauri-apps/tao pull request #240
Opened 2021-11-09 18:44 UTC by wravery

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2021-11-09 18:54 UTC, wravery commented
This should fix #239 (linking the issue).

2021-11-10 07:14 UTC, amrbashir requested changes

2021-11-10 07:14 UTC, amrbashir commented on src/platform_impl/windows/util.rs
> +      let b_menu: BOOL = (GetMenu(hwnd).0 == 0).into();
I don't know when did we change this but it should check for non-null. 
```suggestion
      let b_menu: BOOL = (GetMenu(hwnd).0 != 0).into();
```

2021-11-10 07:14 UTC, amrbashir approved these changes
Thanks!

2021-11-10 08:55 UTC, wusyong approved these changes

2021-11-10 08:55 UTC, merged

2021-11-10 14:07 UTC, lucasfernog commented
Is anyone doing the same on wry and tauri? I can do it if no one is already on it.

2021-11-10 16:11 UTC, wravery commented
Yes, I've got a branch for wry and tauri itself ready. I was just waiting for the merge commit ID so I can update the Cargo.toml references to tao.