Set activation policy at runtime
tauri-apps/tao pull request #353
Opened 2022-03-28 03:14 UTC by betamos

There's already a set_activation_policy API, but it's at build time only. This change simply adds an equivalent for runtime use -- using the standard OS X API (just like show/hide application does today). Thanks!

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-03-28 08:01 UTC, amrbashir requested changes
I guess we merged #298 into next only and not to dev.

I am still not sure why winit devs chose to require activation policy to be set before the event loop runs. I am not experienced with macOS so I don't exactly know the side effects of this but here is an interesting comments from winit devs:
https://github.com/tauri-apps/tao/blob/34be12dc7aa4e60d11498af329b269b36de7c398/src/platform_impl/macos/app_state.rs#L470-L472

2022-03-28 08:01 UTC, amrbashir commented on .changes/add-runtime-activation-policy-mac.md
> +Add `set_activation_policy` as a runtime API.
```suggestion
Add `set_activation_policy_at_runtime`.
```

2022-03-28 08:01 UTC, amrbashir commented on src/platform/macos.rs
> +  fn set_activation_policy(&self, activation_policy: ActivationPolicy);
```suggestion
  fn set_activation_policy_at_runtime(&self, activation_policy: ActivationPolicy);
```

2022-03-28 08:01 UTC, amrbashir commented on src/platform/macos.rs
> +  fn set_activation_policy(&self, activation_policy: ActivationPolicy) {
```suggestion
  fn set_activation_policy_at_runtime(&self, activation_policy: ActivationPolicy) {
```

2022-03-28 17:41 UTC, betamos commented
Wow, that PR was almost identical and I had no knowledge about it. It does have examples and docs though, so it's preferable to mine. Let's replicate that change instead.

What's the difference between next and dev branches, and what processes should be followed to get changes across different branches?

2022-03-28 17:42 UTC, FabianLars commented
@betamos the next branch is currently inactive so don't worry about it. It was our main branch while dev was frozen because of the audit.

2022-03-28 18:59 UTC, betamos commented
On closer look, it appears as the other PR had a bug where the type was wrong - it uses the Rust-defined `ActivationPolicy` enum instead of `NSApplicationActivationPolicy`. I assume it went under the radar due to unsafe-ness in the `msg_send!` macro.

I included Kasper's docstrings in my PR instead. Since it never made it to the `dev` branch, we can just use this PR instead? PTAL.

2022-03-28 21:10 UTC, amrbashir requested changes

2022-03-28 21:10 UTC, amrbashir commented on .changes/add-runtime-activation-policy-mac.md
> +Add `set_activation_policy_at_runtime`.
```suggestion
Add `EventLoopWindowTargetExtMacOS::set_activation_policy_at_runtime`.
```

2022-03-29 02:09 UTC, amrbashir approved these changes, later dismissed

2022-03-29 14:18 UTC, wusyong commented
Could you format it via `cargo fmt`?
It's good to me too and I'll merge it once it's done.

2022-03-29 20:50 UTC, betamos commented
Thanks. Done!

2022-03-30 07:20 UTC, wusyong approved these changes

2022-03-30 07:20 UTC, merged