feat: added text support to system tray - macos, closes #65
tauri-apps/tao pull request #369
Opened 2022-04-19 01:08 UTC by BenJeau

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

Here's an example of the change, closes #65 

https://user-images.githubusercontent.com/22248828/163900111-fadff001-1de9-42e6-b4d1-1332c0eb2985.mov

As this is my first contribution to tauri, please let me know of anything that needs to be done/changed for this to be accepted to be merged

2022-04-19 02:46 UTC, amrbashir requested changes
Thanks, just a small change needed.

2022-04-19 02:46 UTC, amrbashir commented on src/system_tray.rs
> +
This should be in `SystemTrayExtMacOS` trait and you should make a builder variant for `SystemTrayBuilderExtMacOS`. 

You can find them in `src/platform/macos.rs`

2022-08-07 18:31 UTC, patrick91 commented
this looks very promising, is there any way I can test this in my app? :)

2022-09-09 07:10 UTC, vojty commented
Since I'm waiting for this feature as well I created a new PR https://github.com/tauri-apps/tao/pull/554

The changes are the same as in this PR, I've just moved things to the existing traits as @amrbashir suggested and added support for the builder variant.

2022-09-10 18:18 UTC, amrbashir commented
closed in favor of #554. Thanks @BenJeau and @vojty

2022-09-10 18:18 UTC, closed without merging