feat: probe libappindicator or libayatana-appindicator at runtime
tauri-apps/tao pull request #404
Opened 2022-05-24 14:31 UTC by henry40408

closes tauri-apps/tauri#3859

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-05-24 15:26 UTC, amrbashir requested changes
Thank you! A couple of nitpicks and could you add a changefile in `.changes` directory?

2022-05-24 15:26 UTC, amrbashir commented on src/platform_impl/linux/system_tray.rs
> +  return true;
```suggestion
  pkg_config::probe_library("ayatana-appindicator3-0.1").is_ok()
```

2022-05-24 15:26 UTC, amrbashir commented on src/platform_impl/linux/system_tray.rs
> +  return true;
```suggestion
pkg_config::probe_library("appindicator3").or(
  pkg_config::probe_library("appindicator3-0.1")
).is_ok()
```

2022-05-24 15:33 UTC, FabianLars commented
The problem with this approach is that the dev machine needs to have both libs installed. This makes compiling on, for example, fedora completely impossible because libayatana isn't available.

2022-05-24 16:55 UTC, lucasfernog commented
My intent when I added both feature flags is that we only probe at runtime if both are enabled, or we add a third feature flag (`runtime-tray` idk).

2022-05-25 05:05 UTC, wusyong commented
@FabianLars What about we move this to [libappindicator-rs](https://github.com/tauri-apps/libappindicator-rs)?
The reason it will panic is because both crate check in build script. Maybe we can change how libappindicator-rs checks it.
Probing on runtime don't need the lib actually installed.

2022-05-25 12:24 UTC, FabianLars commented
Wouldn't we end up here https://github.com/tauri-apps/libappindicator-rs/pull/28#issuecomment-1063791225 again?
I don't know much about this stuff btw

2022-05-26 06:36 UTC, wusyong commented
That one is during compile time. After searching a bit, I found a crate similar to dlopen.
We might use it to bind both old and ayatana one.
I'll close this in favor of https://github.com/tauri-apps/libappindicator-rs/issues/31

2022-05-26 06:36 UTC, closed without merging