feat: support child window on linux, closes #273
tauri-apps/tao pull request #415
Opened 2022-06-04 06:15 UTC by keiya01

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-06-07 04:44 UTC, wusyong commented
Tested it and looking great! Thanks!
I think at this rate we could bring this method to general window builder method?
This feature isn't relevant to mobile afaik.

2022-06-07 07:27 UTC, vdvman1 commented
If it is made a general window builder method, it would probably be best to document the behaviour differences for each platform, if there are any.
I know at the very least that "child window" on MacOS and Windows have different behaviour, where the "child window" behaviour on MacOS is more akin to "owned window" in Windows, AFAIK

2022-06-08 13:48 UTC, keiya01 commented
I fixed these reviewt.
Thank you for reviewing!

2022-06-09 01:15 UTC, vdvman1 commented
Might be good to use `OwnedBy` on windows rather than `ChildOf`, as I believe that would be more consistent window behaviour with the other platforms (I'm not sure though, that should probably be tested, I haven't/can't test how it behaves on each platform myself)

2022-06-09 03:33 UTC, wusyong commented
It's look good to me but I feel like @amrbashir is best to review the difference between `OwnedBy` and `ChildOf`

2022-06-09 09:02 UTC, amrbashir commented
as @vdvman1 said, `ChildOf` on Windows doesn't behave like other platforms. `OwnedBy` is the closest to other platforms.

With that said, I don't think it is a good idea to provide a general builder method for all 3 platforms. Instead we should have them under extensions trait so macOS would have `WindowBuilderExtMacOS::with_parent`, and Windows  would have `WindowBuilderExtWindows::with_parent` and `WindowBuilderExtWindows::with_owner` and Linux would have `WindowBuilderExtLinux::with_transient_for`.

2022-06-09 10:12 UTC, keiya01 commented
I see.
There are some slight difference between these three methods.
If we split these method for each platform, users may not be confused.

2022-06-09 11:32 UTC, FabianLars commented
On a somewhat off-topic note, can you do normal pushes instead of force-pushing in the future? Would make it much easier to follow along :)

Imo we should add this to our contributing guidelines too 🤔

2022-06-09 12:25 UTC, keiya01 commented
> On a somewhat off-topic note, can you do normal pushes instead of force-pushing in the future? Would make it much easier to follow along :)

Oh, sure.
Thank you for your advice 🙇‍♂️

> Imo we should add this to our contributing guidelines too 

yeah even if we separate these method, I think we should keep a context as comment.

2022-06-09 12:27 UTC, wusyong commented
@keiya01 So sorry you have to revert. I think this is the part I'll usually miss some context.

@FabianLars I'm okay with both as long as commits are clear. I also will do some force push if commits are all just want to make clippy and fmt happy.

2022-06-09 13:31 UTC, keiya01 commented
I reverted in [Revert "fix: ganeral window builder"](https://github.com/tauri-apps/tao/pull/415/commits/0fa2d6c2bc43aa110c817ab787b2e81d5332f771).
BTW by bundling commit with force push, I somtimes be eased to revert lol

2022-06-09 13:52 UTC, keiya01 commented
I will add some description later.

2022-06-09 13:56 UTC, amrbashir requested changes

2022-06-09 13:56 UTC, amrbashir commented on src/platform/unix.rs
> +  fn with_parent_window(self, parent: gtk::ApplicationWindow) -> WindowBuilder;
```suggestion
  /// Set this window as a transient dialog for `parent`
  /// <https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.Window.html#method.set_transient_for> 
  fn with_transient_for(self, parent: gtk::ApplicationWindow) -> WindowBuilder;
```

2022-06-10 05:19 UTC, keiya01 commented
I wonder why does android fail...

2022-06-10 16:35 UTC, wusyong commented
Probably github CI being funny again. I'll rerun it tomorrow.

2022-06-11 03:27 UTC, wusyong commented
Looks like it's because of https://github.com/rust-windowing/android-ndk-rs/pull/286
Let's ignore this for now. I'll update ndk later.
@amrbashir Does this look good to you?

2022-06-11 06:36 UTC, amrbashir approved these changes

2022-06-13 07:11 UTC, merged