feat: added text support to system tray for macos, closes #65
tauri-apps/tao pull request #554
Opened 2022-09-08 19:40 UTC by vojty

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

This is just my attempt to finish the work introduced in https://github.com/tauri-apps/tao/pull/369, all credits go to @BenJeau

2022-09-10 16:38 UTC, amrbashir requested changes
Thank you for taking this feature to the finish line, just a few nit-picks to go.

2022-09-10 16:38 UTC, amrbashir commented on examples/system_tray.rs
> +  let menu_item = tray_menu.add_item(MenuItemAttributes::new("Item 1"));
```suggestion
  let menu_item = tray_menu.add_item(MenuItemAttributes::new("Set tray title (macos)"));
```

2022-09-10 16:38 UTC, amrbashir commented on examples/system_tray.rs
> +      .add_item(MenuItemAttributes::new("Item 2"))
```suggestion
      .add_item(MenuItemAttributes::new("Menu Item with icon"))
```

2022-09-10 16:38 UTC, amrbashir commented on src/platform/macos.rs
> +  /// Sets the tray menu title
```suggestion
  /// Sets the tray icon title
```

2022-09-10 16:38 UTC, amrbashir commented on src/platform/macos.rs
> +  /// Sets the tray menu title
```suggestion
  /// Sets the tray icon title
```

2022-09-10 16:38 UTC, amrbashir commented on src/platform_impl/macos/system_tray.rs
> +      let _: () = msg_send![button, setImagePosition: 2]; // https://developer.apple.com/documentation/appkit/nscellimageposition/nsimageleft
extract this value into a const variable and add the URL as a doc comment

2022-09-10 18:01 UTC, amrbashir approved these changes

2022-09-10 18:15 UTC, merged

2022-09-13 23:32 UTC, BenJeau commented
Thanks @vojty for updating my initial PR and having it merged :)

2022-09-14 07:18 UTC, vojty commented
@BenJeau np, you did the hard work anyway :) However, I didn't realize that we need to expose this new API to `tauri` as well. Any help here https://github.com/tauri-apps/tauri/pull/5182 would be appreciated.