feat(macos): support to change tray icon aspect ratio, close #564
tauri-apps/tao pull request #565
Opened 2022-09-23 05:58 UTC by zzzgydi

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-09-23 12:12 UTC, amrbashir requested changes
I think we should just remove the hard-coded values and use the passed image height and width directly without modifications to match other platforms.

2022-09-23 16:53 UTC, zzzgydi commented
Will there be a breaking change if we use the icon width and height directly?

2022-09-23 16:56 UTC, amrbashir commented
No, since other platforms already have this behavior. We just need to confirm that the `system_tray` example looks the same after/before the change. I mean the icon is not blurry and is not bigger than other tray icons.

2022-09-23 17:39 UTC, zzzgydi commented
<img width="151" alt="image" src="https://user-images.githubusercontent.com/27361820/192025071-ae9858e9-6b0a-4eb4-8cda-945647d0c1e2.png">

It will bigger than other tray icons on macOS, I think the height should be 18.

2022-09-23 18:07 UTC, amrbashir commented
maybe try keeping the height fixed to 18.0 and calculate the width dynamically based on ratio of the original height to the fixed height so it would be something like this

```rs
let height = 18.0;
let width = icon.width / (icon.height / height);
```

2022-09-25 12:16 UTC, amrbashir approved these changes

2022-09-25 12:16 UTC, merged