fix(menus): macOS Services menu not working, closes #243
tauri-apps/tao pull request #569
Opened 2022-09-24 23:54 UTC by caesar

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
closes #243

2022-09-25 12:26 UTC, amrbashir approved these changes

2022-09-25 12:26 UTC, amrbashir requested changes
missing changefile

2022-09-25 15:51 UTC, caesar commented
> missing changefile

Wait, there are changefiles now? Nice!

2022-09-25 18:33 UTC, amrbashir approved these changes

2022-09-25 18:36 UTC, merged

2022-09-25 18:36 UTC, amrbashir commented
thank you

2022-11-11 09:11 UTC, wanghui94 commented
<img width="472" alt="image" src="https://user-images.githubusercontent.com/37385554/201306169-c5732b63-3407-4c9a-acad-bca973c87a30.png">

Is this divider redundant?

2022-11-11 10:40 UTC, caesar reviewed
> Is this divider redundant?

It is indeed redundant. When I implemented this I wasn't sure how to solve it, but I have since found the solution, which is simply to change `NSMenu::alloc(nil)` to `NSMenu::new(nil)` as shown in the code review below.

2022-11-11 10:40 UTC, caesar commented on src/platform_impl/macos/menu.rs
> +        let services_menu = NSMenu::alloc(nil).autorelease();
```suggestion
        let services_menu = NSMenu::new(nil).autorelease();
```

2023-01-06 03:00 UTC, wanghui2021 commented on src/platform_impl/macos/menu.rs
> +        let services_menu = NSMenu::alloc(nil).autorelease();
when will this be fixed？