fix: don't panic if primary monitor not discoverable.
tauri-apps/tao pull request #705
Opened 2023-02-21 23:20 UTC by 2e0byo

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [x] This PR will resolve #704 
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### Other information

2023-02-21 23:48 UTC, amrbashir approved these changes

2023-02-21 23:49 UTC, amrbashir requested changes
Could you also add a change file?

see https://github.com/tauri-apps/tao/blob/dev/.changes/linux-arrow-cursor.md for an example.

2023-02-22 12:45 UTC, wusyong approved these changes

2023-02-22 12:51 UTC, 2e0byo commented
I confess I don't understand the covector ci fail.  What should be in the changes file?

2023-02-22 12:54 UTC, FabianLars commented
it's missing some `-`. There is only `--` while it must be `---` like this
```
---
"tao": patch
---

```

2023-02-22 15:29 UTC, merged