Support right-to-left layout on Windows
tauri-apps/tao pull request #762
Opened 2023-07-07 09:37 UTC by abdnh

### What kind of change does this PR introduce?

This PR adds support for setting right-to-left layout on Windows using the [WS_EX_LAYOUTRTL](https://learn.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles) extended style and others. My main use for this is to make menus appear to the right in an Arabic app. I plan to add support for this to Tauri.

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### Other information

2023-07-10 02:54 UTC, wusyong commented
Let's make this platform-specific method if this is only for Windows.

2023-07-10 16:07 UTC, abdnh commented
It should be possible to implement on Linux and macOS at least. I'll need macOS support in my app in the future so I might add that too then (currently don't have the time to investigate it and want to get Windows support merged as soon as possible). 

Will make it a platform-specific method and add a .changes file.

2023-07-11 10:25 UTC, wusyong requested changes

2023-07-11 10:25 UTC, wusyong commented on src/platform_impl/windows/window_state.rs
> +        const RTL = 1 << 22;
```suggestion
        const RIGHT_TO_LEFT_LAYOUT = 1 << 22;
```

2023-07-11 10:25 UTC, wusyong commented on src/platform/windows.rs
> +  /// Sets right-to-left layout.
Could you explain more about this layout in this documentation?

2023-07-17 10:54 UTC, amrbashir approved these changes

2023-07-17 10:54 UTC, amrbashir commented
Oh looks like you didn't sign your commits and I can't merge the PR unless they are signed. You need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928) for example.

2023-07-17 12:14 UTC, abdnh commented
Actually signed off the first commit and then forgot to sign the rest. Should be fine now I guess.

2023-07-17 12:55 UTC, amrbashir approved these changes

2023-07-17 14:41 UTC, wusyong approved these changes

2023-07-17 14:41 UTC, merged