feat(windows): allow setting window class name, closes #769
tauri-apps/tao pull request #770
Opened 2023-07-25 15:34 UTC by geraudloup

allow to customize the window class name instead of current value hard coded "Window Class"

Currently, on Windows, all windows created by Tao have the same class Window Class, it would be neet to allow for customization of the Windows' window class name. One use case: some windows custom hotkey managers leverage window class names to select windows...

Waiting for merge in upstream project winit (pass all 55 checks) : https://github.com/rust-windowing/winit/pull/2978
(closing mirrored issue https://github.com/rust-windowing/winit/issues/2977)

### What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### Checklist
- [X] This PR will resolve #769 
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary
- [X] It can be built on all targets and pass CI/CD.

2023-07-26 23:11 UTC, amrbashir requested changes
Thanks for your contribution, could you also add a changefile in .changes directory?

2023-07-26 23:11 UTC, amrbashir commented on src/platform_impl/windows/window.rs
> +unsafe fn register_window_class<T: 'static>(window_classname: &String) -> Vec<u16> {
```suggestion
unsafe fn register_window_class(window_classname: &str) -> Vec<u16> {
```

2023-07-26 23:11 UTC, amrbashir commented on src/platform_impl/windows/window.rs
> +  let class_name = register_window_class::<T>(&pl_attribs.window_classname);
```suggestion
  let class_name = register_window_class(&pl_attribs.window_classname);
```

2023-07-28 09:35 UTC, geraudloup commented
> Thanks for your contribution, could you also add a changefile in .changes directory?

Yes ! I added one (following the exemple of `windows-ltr.md`) and tested and accepted your suggested changes (I also updated my PR on winit with your improvements) !

2023-07-28 12:39 UTC, amrbashir approved these changes

2023-07-28 12:40 UTC, merged

2023-07-28 12:42 UTC, amrbashir commented
@wusyong should this API be ported to the v0.16 branch or wait until tauri v2?

2023-08-15 14:03 UTC, amrbashir commented
cherry picked into v0.16 in https://github.com/tauri-apps/tao/commit/ae664f05daf10456b4721214372bb5409abe53b9